### PR TITLE
Michael

### PR DESCRIPTION
**Pull request by michael-fuest**
Added timeseries analysis and cleaned up the exploration file.

### CODE REVIEW

**Comment by RichardJasansky** [comment]
Great approach, nice results, nothing more to say!

**Review by RichardJasansky — DISMISSED** [review]

**Review by nick-beep — DISMISSED** [review]

**Review by NickKnappstein — APPROVED** [review]
Srry. logged in with a false account to approve.

**Review by RichardJasansky — APPROVED** [review]
Looks good

**Review by NickKnappstein — APPROVED** [review]
Really great work! Also with the readme as a starting point.

**Pull request merged**
