### PR TITLE
Michael

### PR DESCRIPTION
**Pull request by michael-fuest**

### CODE REVIEW

**Comment by michael-fuest** [comment]
No substantial changes have been made since our last update call (aside from adding prices per kwh)

**Review by dominik-99 — COMMENTED** [review]
Nice

**Review by NickKnappstein — APPROVED** [review]
Great work!

**Review by NickKnappstein — APPROVED** [review]

**Review by dominik-99 — COMMENTED** [review]
done!

**Review by dominik-99 — APPROVED** [review]
done!

**Review by RichardJasansky — APPROVED** [review]

**Pull request merged**
